### ISSUE TITLE
Fullscreen header broken when JavaScript disabled

### ISSUE THREAD

**Issue by MarkBennett** [amaabca/ama_layout#232]
# Steps To Reproduce
1) Visit http://ama-layout.herokuapp.com/
2) Disable JavaScript
3) Reload
4) Header is broken

In Chrome Version 62.0.3202.94 (Official Build) (64-bit)
<img width="1552" alt="screen shot 2017-12-08 at 14 50 16" src="https://user-images.githubusercontent.com/61872/33786699-4a553a7a-dc27-11e7-83bc-1af314bd88f4.png">

In FirefoxDeveloperEdition 58.0b9 (64-bit)
<img width="1552" alt="screen shot 2017-12-08 at 14 51 16" src="https://user-images.githubusercontent.com/61872/33786700-4a9d0094-dc27-11e7-9a3c-f55fa31821e5.png">

# Expected result
I would expect the header to bar to not overlap the notice about JS being disabled.

**Comment by MarkBennett** [comment]
I looked at this a little more...

I think it's actually an issue with the <div class="title-bar" data-hide-for="large" data-responsive-toggle="main-menu"> not getting display: none when JS is disabled.

Maybe it could be fixed by using display: none by default for this instead?

**Comment by ryanjones** [comment]
Closing - We don't support non-JS browsers at this point in time.
